title: PhearZero.com
email: github@phearzero.com
author:
  twitter: PhearZero
twitter:
  username: PhearZero
  card: summary
logo: /assets/imgs/Skull-640.png
theme: jekyll-theme-hacker
google_analytics: UA-129663883-2
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-octicons
exclude:
 - .idea/
 - nodejunkie.github.io.iml
 - node_modules