title: PhearZero.com
url: https://phearzero.com
email: git@phearzero.com
logo: /assets/imgs/Skull-640.png
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-octicons
  - jekyll-sitemap
  - jekyll-pwa-plugin
include:
  - .wiki
  - CHANGELOG.md
exclude:
 - .idea/
 - phearzero.github.io.iml
 - node_modules
 - package.json
 - package-lock.json
 - LICENSE
 - CNAME
 - Gemfile
 - Gemfile.lock
 - phearzero.github.io.gemspec
 - CHANGELOG
